### ISSUE TITLE
update functionality for 'VisualState' class

### ISSUE THREAD

**Issue by AustinGPowerz** [compmem/smile#164]
The 'MouseCursor' visual state does not have robust functionality to update state parameters in experimental run time. This functionality is available to 'WidgetState' but not 'VisualState'. 

example code of alternating argument that will throw error:

```python
exp = Experiment()
with Parallel():
    mouse = MouseCursor(filename=None)
    with Loop():
        UpdateWidget(mouse, filename="C:/Users/mcemc/OneDrive/Pictures/erging boathous.jpg")
        Wait(1.0)
        UpdateWidget(mouse, filename=None)
        Wait(1.0)
exp.run()
```
Attribute Error: 'MouseCursor' object has no attribute 'live change' 

See the 'target' parameter in the 'UpdateWidget' class, as well as the 'live_change' and 'update' functions in the 'WidgetState' class. 

Suggested changes:
- change 'UpdateWidget' docs from 'VisualState' to "WidgetState' to accurately reflect current behavior.
- implement state update functions for 'VisualStates'.

**Comment by dyld-w** [comment]
Trying to change mouse representation during experiment but can't

**Comment by dyld-w** [comment]
I'm seeing a couple things here:

1. As you identified, a misleading class definition & incorrect docstring for the `UpdateWidget` class. 
2. A missing _feature_ with not being able to change the cursor appearance during an experiment runtime.

Looks like you stumbled into 1 in hopes of finding the opposite of 2. 

Prioritizing stability enhancements, I'm choosing to aim this issue at bullet 1: cleaning up the `UpdateWidget` class implementation & documentation. You correctly identified that the `live_change` function `UpdateWidget` is attempting to call is not part of `VisualState` but rather part of `WidgetState`. As such, `UpdateWidget` currently only works against `WidgetState` objects & does not work for other states that inherit `VisualState` including `MouseCursor` and `BackgroundColor`. I'll work on updating `UpdateWidget` to reflect this behavior.

I've noted the ability to change the appearance of the mouse cursor during an experiment runtime as a functionality to implement down the line.

**Comment by dyld-w** [comment]
Issued a pull request with a fixed docstring & a type check to address 1: https://github.com/compmem/smile/pull/165

While the feature to change cursor appearance during an experiment runtime is in development to address 2, see https://github.com/compmem/smile/blob/master/docs/examples/mouse_tracking.py for a start on a workaround: animating widgets based on mouse position.
